language: node_js
addons:
  apt:
    packages:
    - lftp
node_js:
- '5'
- '4'
install:
- gem install scss_lint
- npm install
script:
- npm run lint
- npm run test
- npm run build
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy
env:
  global:
  - secure: BL6UvT6qYRxVUDV4W1/ctdTDKeFUf7LK4Gxv8f/VfZAj5DclYpgcr7S6bOjMxlnwvNgRJGQKUqVL+o0oHM8DXz2U4NJIFLo75RSHx/unnWVl3pns6PK/dIcsLgu9ZtqGS3GdIArmxTb1dFCOqOIMPE5vMvkUTn0neUar5Lym5Sc54QBh4PLPgxa/Rqy1BAeG22dI++5VYN3YY9e7EX1bkPdR+pN1sBSENdP7rjyUsx/2SHe5rDqOAykmTRV3l+oZeojBalXY27Wn5d5Lsr1nnkTLP+ZlO0b5HBehzX7+uaE0KP0QDbvC+Y9ruej7tk31WRji0yspcLzunhM/G+nc0z8fATBA/7TWTiPCXT9ecPIaBb0HOlrJF/jq3hhi1OfiCdcRP8krYHaGIjjdf+vvb/ko5egbUG8/RqhRWhAJ0NyB/T7MNfwyPDY0zaMZ+qU0xhq6EXBJNZqbhwHDbiQko47FlDFwDi4OLoWUTVXDAjbzPDv7leo+uCIIJdWUJt8gsZWebow6s7fSvPzzbCZNZBV2Eh3bSSb95tMpSBZmHp2D3YcBUqvGHB8ysR3kzyWiY9AJ6BRIHtRIBV3zINxUcffP0R/JleKjiZuC02b5AAuCLEylBg0/oDfx2L1iDsxreLxIeVqI++VUl5Ftl+sHk7QaxOtPtewayz+c9sCXGVc=
  - secure: W6I0F7ohq/lQ8KcI1a2NANXPWydQfXnE3D17vWBCfk2Bm7+hDvb1jSeQQtBcmMOLcfZizC6jWR+xeu73sz/9yVCrZfAJ+iBKLs8gD2BshRWA0/kMONjncBxgz3tQ4r79RTWraiEHzFYiFUzRX/YSNf8WpFk/2vPygdf+IdmhGJgh7BhXV9RpVvYpuVy9D9GWiRuLxVp0fQG0UJor/hBN5uQhViEo/OJE+MvNEPdNIFLoyuuk+mtiVmeGwwRnsOaU4BazYc8/WVH2Uq1oIZ30fAtv4nkwUOkWo7/Hs57d0KlV2KfnUHZ9YL0ELK45IgoAkT9UJVDQJhqRxgEMmucf4HBBNAe5uTWrJZiVLhxWT2LksCdlrCaI4UjepfORAkczD7zUaJIu/PUjhJJ3FmFXSWSPhTxw2xo6PZU1dalbu5A1PYx0o9hb55Vg9LU6ysrpQasGVvP1YM3tFd3ynC8Y8SGtis7rUWqn6zHsC9GmGYoOQNC6X9cQF3C4mRO9vcatRLosHWsKrNLildyjGCeI3tkvigujr5bXtzAgQ0qpTI8BSBGSZMbHBtEYX9LaYw73Ru6zDZkRTSSe0mS69uOj+8i475BZ8zrPxZcjF8v28aUEJe/Ku9Mfam0DxRLhjLN8IOpy02w8BWzYqQh6z/+i6q5yUgd8afcnUH7i7LIidnQ=
  - secure: InFBdZj9XmFZpCgw1jRoUGCXthORmUuvo/afwGDTnmFKl22NSnwQajJJB3ZUcOLoGlEcnQKLwOrHSLmPm2C4oyAcKgdfiFyAhjUwJszwikpRn02TnMBrc59+GLeWcdvXb0gLAO9KMyfgPAdskf58euVcJKUQkC197agwLYeYBDnEUg6kyWXIyB2O7htuJpH/ONB315vxS4MvOaezBgNPr6UiHTBGwKGabUNTXWnsD3UzXNmFL/Cbn14k+RJDnO/WAIqncZqunMLpmem1yebry0dN3CqIceiNuH0VbnrdxCoZDTuZlgA6/BIAd1JWO/yEzMtXj5A68XZtfy2kEBlta7q1oAn/PaASHUTpN+fshWDTf0eELbmLDHFVE/Ox2JsvoeEacd2HlkgJ/OpeejEKYnT2GayHISaIrh64PpaoWWy5cQls5sauEBoiemEkrcYCTzQQZ968uQDENobuTcURQUtXni/c7VBqDeNA/SnXz7EmE5GvYnjbMvIBvYK47WL3PwmKrNVjIi0oFGQGSqDW45SJFjeDPH6J7RrAGCkOykIkamuG6pgLpLEIrL2axvss4Eulc7F+w/nQ1Y2OHwcZFRQ8b1wilatdFUZR/gaIhtNCNRWm+Vq1nTXg15yUXLd5+J/JRS5iQoWEVWRrnZSpqQuStYcmLWzVFkV5Fg56sTg=
