language: node_js
addons:
  apt:
    packages:
    - sshpass
node_js:
  - "5"
  - "4"
install:
  - gem install scss_lint
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sshpass -e scp -r -o stricthostkeychecking=no dist/* $DEPLOY_DEST
env:
  global:
    - secure: IY7gJTrzYyqtX62oe65zSdCQjsLj8+FwOAY5Xf6nnJNhYx3lN0OWpVqxulsNLB4ErGFqeOivswHorW3FEBrleFfsM92f4x9mPcxH7HEFs3dWjTK6aDWsq6PxEVUpMNg3YgKAzs29Y3MdSDUUC6BPpnaHOwF8Qt9cq1UaUDqRRyLFZ33Hn0cM0mvrLuM9i7u7ePRRAZzvorlXWzqpjyjdUoE2FkqSoW0BHXFicHb9mLxVzSrFfpZPHmI9CCtr7QD5WPlfXHDsBlnAQE1vHKQ5hQSedg/jXGiX4jEYYXhY5mw7lhJ8Y3nAriESzFj54yvt4dtey5sQh3AZaKNRNCYaIfylxuMnb7k4PN2wPJSvA2qVaM9bxD1Y1FjBdSgExxACjscSgGCCPSe0r6fdK8+et0ewjOj6PZrSocH5kTqTaj87CcRpqTqeJXVKTGTQutxdfZ1HDoF1Yqsgw10uWyyESW6VoK33v1kx9IrpeJVFzqUzv1NLz5MkSpUquujyy+tcjPwz3YQIQv5uzBrBs0YQegYZ59U+jVjoYHGB0kkeuyeQfg37pLBii39Bcuu4prDgCpc2HGIVnAiRd1wIbbCpfmVdV6fRZ/0PaP/IFguNK3UPIPF4rWYA2MsCqIvqJzKUcVIXLOq7g/0cQrFiLPisaVwnK7yHjP2l/JkMZO3mKls=
    - secure: J7sLlUJtyIeRJ9AH/7wyim0YJ85vfihM1/GB65N6QZcp8eqgV9DybYCJ58hMWxkb6w/Uigs9luBTi02ePukvbO1aOasJz6O1Zav3uJQlMsab/SMU+Ulf0Wpvcx7IBUfec11TaLZqZnRk9GaVYXLPylKBaHT6DUBNB0Ugc8AeWKy159IfnOkn1xY9YjVVbPqW8g+UO5S1c+8MO0NU1t1STTHkcEeynrT2aCN7WiUZgoIPf7sOVIG3vc/ELCRUp850Ixgf8b0kaUBU0u2Q6JfFjxTLrN+j116S4NPeTbWBfG94XTWwSPQXyxtKExhj4cF5sx0+JuGz1El+vQR2+EwFk49AkgfTBP9IYjHE8hjPexcgqKSvB11eolAFjpU7wQmxh7R1+T+26X4WkWpOVglDqSIb8d41PWJOwe5wSK3+FheqPDfCJaeD3U1p1KH4IyRLRyTUpMAHMWGzgzX9fofFIo4fTZA5fEWxunGy5qf92zOJCMvCUrQVgqJlpTH+Cw7rjmDXJJi9uipSDCRRiDpwvyBQLHIuNcxW3hZ9CNAHd0QtJq5F/XelJVWkWPUDlEDRk+p4U6trAIpsWMEV0Unf+1rayIHpnj289u6qN6kOma/yJXIaSGaSXnKHYmtGM+8ZVT+r7mnYMdWFFHJr0sWEkXBuaYbxTtpKMzBF7F7us8g=
